name: Vercel Test Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Test
    steps:
    - uses: actions/checkout@v3
    - uses: bahmutov/npm-install@v1
    - run: npm run lint
    - run: npm run test